# Generated by Django 4.2.6 on 2023-10-18 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_topic_room_host_message_room_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated', '-created']},
        ),

        migrations.RenameField(
            model_name="message",
            old_name="room_id",
            new_name="room"
        )
    ]
